"use client";

import { useState, useEffect } from 'react';
import Link from 'next/link';

type WorkoutEntry = {
  id: string;
  name: string;
  description: string;
  duration: number;
  type: string;
  exercises: any;
  isCompleted: boolean;
  completedAt: string | null;
  createdAt: string;
};

export default function WorkoutsPage() {
  const [workouts, setWorkouts] = useState<WorkoutEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchData = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/workouts');
      if (res.ok) setWorkouts(await res.json());
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, []);

  const handleCreateMockWorkout = async () => {
    try {
      const res = await fetch('/api/workouts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: 'Push Day - Chest & Triceps (AI Gen)',
          description: 'Focus on upper body pushing movements.',
          duration: 45,
          type: 'Strength',
          exercises: [{ name: 'Bench Press', sets: 4, reps: '8-10' }]
        })
      });
      if (res.ok) fetchData();
    } catch (e) { console.error(e); }
  };

  // Find most recent or uncompleted workout
  const activeWorkout = workouts.length > 0 ? workouts[0] : null;

  return (
    <div className="flex flex-col gap-6 lg:gap-8 max-w-7xl mx-auto w-full">
      <header className="flex flex-wrap justify-between items-center gap-4 mb-2">
        <div>
          <h2 className="text-white text-3xl font-bold leading-tight tracking-tight flex items-center gap-2">
            AI Workout Planner <span className="material-symbols-outlined text-primary text-3xl neon-text-glow">auto_awesome</span>
          </h2>
          <p className="text-slate-400 text-sm mt-1">Personalized training generated by FitNexa AI engine.</p>
        </div>
        <button onClick={handleCreateMockWorkout} className="flex items-center justify-center gap-2 rounded-full h-11 px-6 bg-primary text-black text-sm font-bold tracking-wide hover:bg-[#32e612] transition-colors shadow-[0_0_20px_rgba(56,255,20,0.4)]">
          <span className="material-symbols-outlined text-[20px]">magic_button</span>
          Generate New Plan
        </button>
      </header>

      <div className="flex gap-2 flex-wrap">
        <button className="flex h-9 items-center justify-center rounded-full bg-surface-dark border border-white/10 px-5 text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">All</button>
        <button className="flex h-9 items-center justify-center rounded-full bg-primary/20 border border-primary/50 px-5 text-primary text-sm font-medium shadow-[0_0_10px_rgba(56,255,20,0.1)]">Strength</button>
        <button className="flex h-9 items-center justify-center rounded-full bg-surface-dark border border-white/10 px-5 text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">Cardio</button>
        <button className="flex h-9 items-center justify-center rounded-full bg-surface-dark border border-white/10 px-5 text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">Flexibility</button>
        <button className="flex h-9 items-center justify-center rounded-full bg-surface-dark border border-white/10 px-5 text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors">HIIT</button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_350px] gap-8 mt-2">
        {/* LEFT COLUMN */}
        <div className="flex flex-col gap-6">
          
          {/* Weekly Strip */}
          <div className="glass-panel rounded-xl p-2 flex justify-between items-center relative overflow-hidden border border-surface-glass-border shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-primary/5 to-transparent"></div>
            
            {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, idx) => {
              const d = new Date();
              const todayIdx = (d.getDay() + 6) % 7; // Mon=0, Sun=6
              const isToday = idx === todayIdx;
              const loopD = new Date(d);
              loopD.setDate(d.getDate() - (todayIdx - idx));
              const date = loopD.getDate();
              
              const hasWorkout = workouts.some(w => w.completedAt && new Date(w.completedAt).toDateString() === loopD.toDateString());
              
              if (isToday) {
                return (
                  <button key={day} className="flex flex-col items-center justify-center flex-1 py-3 relative z-10 w-full hover:bg-white/5 rounded-lg transition-colors">
                    <span className="text-xs font-bold text-primary mb-1 neon-text-glow">{day}</span>
                    <div className="w-10 h-10 rounded-full bg-primary text-black flex items-center justify-center shadow-[0_0_15px_rgba(56,255,20,0.3)] min-w-[40px]">
                      <span className="text-base font-bold">{date}</span>
                    </div>
                    <div className="w-1.5 h-1.5 rounded-full bg-primary mt-1 shadow-[0_0_5px_rgba(56,255,20,1)]"></div>
                  </button>
                );
              }

              return (
                <button key={day} className="flex flex-col items-center justify-center flex-1 py-3 relative z-10 w-full hover:bg-white/5 rounded-lg transition-colors group">
                  <span className="text-xs font-medium text-slate-500 mb-1">{day}</span>
                  <div className="w-8 h-8 rounded-full flex items-center justify-center text-slate-400 group-hover:text-white transition-colors min-w-[32px]">
                    <span className="text-sm font-bold">{date}</span>
                  </div>
                  <div className={`w-1.5 h-1.5 rounded-full mt-1 ${hasWorkout ? 'bg-primary/50' : 'bg-transparent'}`}></div>
                </button>
              );
            })}
          </div>

          {/* AI Suggestion Banner */}
          <div className="glass-panel rounded-xl p-4 flex flex-col sm:flex-row items-start gap-4 border border-primary/30 relative overflow-hidden shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
            <div className="absolute inset-0 bg-primary/5"></div>
            <div className="absolute -left-10 top-1/2 -translate-y-1/2 w-32 h-32 bg-primary/20 blur-[30px] rounded-full"></div>
            
            <div className="bg-background-dark rounded-full w-10 h-10 flex items-center justify-center text-primary shrink-0 z-10 border border-primary/20 shadow-[0_0_10px_rgba(56,255,20,0.2)]">
              <span className="material-symbols-outlined">psychology</span>
            </div>
            <div className="flex-1 z-10">
              <h4 className="text-white text-sm font-bold mb-1 flex items-center gap-2">
                AI Recovery Insight
                <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-primary text-black uppercase tracking-wider">New</span>
              </h4>
              <p className="text-slate-300 text-sm leading-relaxed">Based on your recent heart rate variability data, increasing rest times between heavy sets by 30 seconds today will optimize your strength output.</p>
            </div>
            <button className="z-10 text-slate-400 hover:text-white mt-1 self-end sm:self-auto">
              <span className="material-symbols-outlined text-sm">close</span>
            </button>
          </div>

          <div className="flex flex-col gap-4">
            <h3 className="text-white font-bold text-lg mb-2">My Workouts</h3>
            
            {/* Card 1: Active Workout */}
            {isLoading ? (
              <p className="text-slate-400 text-sm p-4">Loading workouts...</p>
            ) : workouts.length === 0 ? (
               <div className="glass-panel rounded-xl p-8 border border-white/5 text-center">
                 <span className="material-symbols-outlined text-4xl text-slate-600 mb-2">fitness_center</span>
                 <p className="text-slate-400 mb-4">No workouts found. Click "Generate New Plan" to automatically add one to your profile.</p>
               </div>
            ) : (
               workouts.map((workout) => (
                <div key={workout.id} className="glass-panel rounded-xl p-5 border border-primary/40 relative overflow-hidden group hover:border-primary/60 transition-colors shadow-[0_8px_32px_0_rgba(0,0,0,0.37)] mb-4">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 blur-[40px] rounded-full translate-x-10 -translate-y-10 group-hover:bg-primary/20 transition-all"></div>
                  
                  <div className="flex flex-col md:flex-row gap-5 relative z-10">
                    <div className="flex-1 flex flex-col justify-between">
                      <div>
                        <div className="flex items-center gap-2 mb-2">
                          {workout.isCompleted ? (
                             <span className="px-2 py-1 rounded bg-slate-800 text-slate-400 text-xs font-bold uppercase tracking-wider border border-white/10">Completed</span>
                          ) : (
                            <span className="px-2 py-1 rounded bg-primary/20 text-primary text-xs font-bold uppercase tracking-wider border border-primary/30">Active</span>
                          )}
                          <span className="text-slate-400 text-sm font-medium">{new Date(workout.createdAt).toLocaleDateString()}</span>
                        </div>
                        <h4 className="text-white text-2xl font-bold leading-tight mb-2">{workout.name}</h4>
                        
                        <div className="flex flex-wrap gap-3 mb-5">
                          <div className="flex items-center gap-1.5 text-slate-300 text-sm">
                            <span className="material-symbols-outlined text-[16px] text-primary">timer</span> {workout.duration} min
                          </div>
                          <div className="flex items-center gap-1.5 text-slate-300 text-sm">
                            <span className="material-symbols-outlined text-[16px] text-primary">fitness_center</span> {workout.type}
                          </div>
                        </div>
                        
                        <div className="space-y-2 mb-6 border-l-2 border-slate-700 pl-4">
                          {workout.exercises && Array.isArray(workout.exercises) ? (
                            workout.exercises.slice(0, 3).map((ex: any, i: number) => (
                              <div key={i} className="flex items-center justify-between text-sm">
                                <span className="text-slate-300">{ex.name}</span>
                                <span className="text-slate-500 font-mono">{ex.sets} x {ex.reps}</span>
                              </div>
                            ))
                          ) : (
                             <p className="text-slate-500 text-sm italic">{workout.description || 'Custom generated workout'}</p>
                          )}
                        </div>
                      </div>
                      
                      {!workout.isCompleted && (
                        <button className="flex flex-shrink-0 items-center justify-center gap-2 rounded-full h-11 px-6 bg-primary/10 border border-primary text-primary text-sm font-bold tracking-wide hover:bg-primary hover:text-black transition-all shadow-[0_0_15px_rgba(56,255,20,0.15)] w-full md:w-auto self-start">
                          <span className="material-symbols-outlined text-[20px]">play_arrow</span>
                          Start Workout
                        </button>
                      )}
                    </div>
                    
                    <div className="w-full md:w-[200px] aspect-video md:aspect-[3/4] bg-slate-800 rounded-lg border border-white/10 overflow-hidden relative shrink-0">
                      <div className="absolute inset-0 bg-gradient-to-tr from-slate-800 to-slate-900 flex items-center justify-center">
                        <span className="material-symbols-outlined text-6xl text-white/10">model_training</span>
                      </div>
                      <div className="absolute bottom-2 right-2 bg-black/60 backdrop-blur-sm px-2 py-1 rounded text-xs font-mono text-white flex items-center gap-1 cursor-pointer hover:bg-black transition-colors">
                        <span className="material-symbols-outlined text-[14px] text-primary">play_circle</span> Preview
                      </div>
                    </div>
                  </div>
                </div>
               ))
            )}

            {/* Card 2: Rest Day */}
            <div className="glass-panel rounded-xl p-5 border border-white/5 opacity-80 hover:opacity-100 transition-opacity cursor-pointer">
              <div className="flex flex-col md:flex-row gap-5 items-center">
                <div className="w-14 h-14 rounded-full bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400 shrink-0">
                  <span className="material-symbols-outlined text-3xl">self_improvement</span>
                </div>
                <div className="flex-1 text-center md:text-left">
                  <div className="flex items-center gap-2 mb-1 justify-center md:justify-start">
                    <span className="text-slate-500 text-sm font-medium">Tomorrow • Day 15</span>
                  </div>
                  <h4 className="text-white text-lg font-bold">Active Rest Day</h4>
                  <p className="text-slate-400 text-sm mt-1">Focus on mobility, light stretching, and hydration. Recommended: 15min Yoga flow.</p>
                </div>
                <button className="flex items-center justify-center rounded-full h-9 px-4 bg-slate-800 border border-white/10 text-slate-300 text-sm font-medium hover:bg-white/10 transition-colors shrink-0">
                  View Tips
                </button>
              </div>
            </div>

            {/* Card 3: Future Workout */}
            <div className="glass-panel rounded-xl p-5 border border-white/5 opacity-70 hover:opacity-100 transition-opacity cursor-pointer">
              <div className="flex justify-between items-center gap-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-slate-500 text-sm font-medium">Friday • Day 16</span>
                  </div>
                  <h4 className="text-slate-300 text-lg font-bold">Pull Day — Back & Biceps</h4>
                  <div className="flex gap-3 mt-2">
                    <span className="text-slate-500 text-xs flex items-center gap-1"><span className="material-symbols-outlined text-[14px]">timer</span> 50 min</span>
                    <span className="text-slate-500 text-xs flex items-center gap-1"><span className="material-symbols-outlined text-[14px]">fitness_center</span> 6 Exercises</span>
                  </div>
                </div>
                <button className="w-10 h-10 rounded-full bg-slate-800 border border-white/10 flex items-center justify-center text-slate-400 hover:text-white hover:bg-white/10 transition-colors shrink-0">
                  <span className="material-symbols-outlined">more_horiz</span>
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN */}
        <div className="flex flex-col gap-6">
          
          {/* Quick Stats */}
          <div className="glass-panel rounded-xl p-5 border border-white/5 shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
            <h3 className="text-white font-bold text-base mb-4 flex items-center gap-2">
              <span className="material-symbols-outlined text-primary text-[20px]">electric_bolt</span>
              Weekly Progress
            </h3>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
              <div className="bg-background-dark/50 rounded-lg p-3 border border-white/5">
                <p className="text-slate-400 text-xs font-medium mb-1">Workouts</p>
                <div className="flex items-end gap-2">
                  <span className="text-white text-2xl font-bold leading-none">3</span>
                  <span className="text-slate-500 text-sm leading-none pb-0.5">/ 5</span>
                </div>
                <div className="w-full h-1.5 bg-slate-800 rounded-full mt-3 overflow-hidden">
                  <div className="h-full bg-primary w-[60%] rounded-full shadow-[0_0_5px_rgba(56,255,20,0.5)]"></div>
                </div>
              </div>
              
              <div className="bg-background-dark/50 rounded-lg p-3 border border-white/5">
                <p className="text-slate-400 text-xs font-medium mb-1">Total Time</p>
                <div className="flex items-end gap-2">
                  <span className="text-white text-2xl font-bold leading-none">2.5</span>
                  <span className="text-slate-500 text-sm leading-none pb-0.5">hrs</span>
                </div>
                <div className="flex items-center gap-1 mt-2">
                  <span className="material-symbols-outlined text-[14px] text-primary">trending_up</span>
                  <span className="text-primary text-xs font-medium">+15% vs last wk</span>
                </div>
              </div>
            </div>
          </div>

          {/* Muscle Focus */}
          <div className="glass-panel rounded-xl p-5 border border-white/5 flex flex-col items-center shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
            <h3 className="text-white font-bold text-base w-full mb-4">Muscle Focus (Current Block)</h3>
            <div className="w-48 h-48 relative my-2">
              <div className="absolute inset-0 bg-background-dark/30 rounded-full border border-white/10"></div>
              <div className="absolute inset-4 bg-background-dark/40 rounded-full border border-white/10"></div>
              <div className="absolute inset-8 bg-background-dark/50 rounded-full border border-white/10"></div>
              
              <div className="absolute top-0 bottom-0 left-1/2 w-px bg-white/10 -translate-x-1/2"></div>
              <div className="absolute left-0 right-0 top-1/2 h-px bg-white/10 -translate-y-1/2"></div>
              <div className="absolute top-0 bottom-0 left-1/2 w-px bg-white/10 -translate-x-1/2 rotate-45"></div>
              <div className="absolute top-0 bottom-0 left-1/2 w-px bg-white/10 -translate-x-1/2 -rotate-45"></div>
              
              <div className="absolute inset-0 bg-primary/20 backdrop-blur-[2px] border border-primary/50" style={{ clipPath: 'polygon(50% 10%, 85% 30%, 90% 65%, 70% 90%, 30% 85%, 15% 50%, 30% 20%)', boxShadow: '0 0 20px rgba(56,255,20,0.1) inset' }}></div>
              
              <span className="absolute -top-6 left-1/2 -translate-x-1/2 text-[10px] text-slate-400 font-medium whitespace-nowrap">Chest</span>
              <span className="absolute top-[20%] -right-8 text-[10px] text-primary font-bold neon-text-glow whitespace-nowrap">Back</span>
              <span className="absolute bottom-[20%] -right-8 text-[10px] text-slate-400 font-medium whitespace-nowrap">Legs</span>
              <span className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-[10px] text-slate-400 font-medium whitespace-nowrap">Core</span>
              <span className="absolute bottom-[20%] -left-8 text-[10px] text-slate-400 font-medium whitespace-nowrap">Arms</span>
              <span className="absolute top-[20%] -left-[40px] text-[10px] text-slate-400 font-medium whitespace-nowrap">Shoulders</span>
            </div>
          </div>

          {/* PR Tracker */}
          <div className="glass-panel rounded-xl p-5 border border-white/5 shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-white font-bold text-base">Recent PRs</h3>
              <span className="text-xs text-primary font-medium bg-primary/10 px-2 py-1 rounded">This Month</span>
            </div>
            
            <div className="flex flex-col gap-3">
              <div className="flex items-center justify-between py-2 border-b border-white/5">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-300">
                    <span className="material-symbols-outlined text-[18px]">fitness_center</span>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white">Bench Press</p>
                    <p className="text-xs text-slate-500">1RM Est.</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <span className="text-white font-mono font-medium">225 lbs</span>
                  <span className="material-symbols-outlined text-[16px] text-primary">arrow_upward</span>
                </div>
              </div>
              
              <div className="flex items-center justify-between py-2 border-b border-white/5">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-300">
                    <span className="material-symbols-outlined text-[18px]">sports_martial_arts</span>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white">Squat</p>
                    <p className="text-xs text-slate-500">3 Rep Max</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <span className="text-white font-mono font-medium">315 lbs</span>
                  <span className="material-symbols-outlined text-[16px] text-primary">arrow_upward</span>
                </div>
              </div>
              
              <div className="flex items-center justify-between py-2">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-300">
                    <span className="material-symbols-outlined text-[18px]">directions_run</span>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white">5K Run</p>
                    <p className="text-xs text-slate-500">Time</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <span className="text-white font-mono font-medium">24:30</span>
                  <span className="material-symbols-outlined text-[16px] text-red-400">arrow_downward</span>
                </div>
              </div>
            </div>
          </div>

          {/* AI Difficulty */}
          <div className="glass-panel rounded-xl p-5 border border-primary/20 shadow-[0_8px_32px_0_rgba(0,0,0,0.37)] bg-gradient-to-b from-background-dark/80 to-background-dark/30">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-white font-bold text-base flex items-center gap-1.5">
                  AI Difficulty
                  <span className="material-symbols-outlined text-primary text-[16px]">tune</span>
                </h3>
                <p className="text-xs text-slate-400 mt-1">Adjust intensity for upcoming sessions</p>
              </div>
              <div className="px-2 py-1 rounded bg-slate-800 border border-white/10 text-xs font-medium text-white whitespace-nowrap ml-2">
                Optimal (7.5)
              </div>
            </div>
            
            <div className="mt-6 mb-2 relative">
              <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden border border-white/5">
                <div className="h-full bg-gradient-to-r from-blue-500 via-primary to-red-500 w-[75%] rounded-full shadow-[0_0_10px_rgba(56,255,20,0.8)]"></div>
              </div>
              <input type="range" className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" min="0" max="10" defaultValue="7.5" step="0.5" />
              <div className="absolute top-1/2 -translate-y-1/2 left-[75%] -translate-x-1/2 w-4 h-4 bg-white rounded-full border-2 border-primary shadow-[0_0_10px_rgba(56,255,20,0.8)] pointer-events-none"></div>
              
              <div className="flex justify-between mt-3 text-[10px] text-slate-500 font-medium uppercase tracking-wider">
                <span>Easy</span>
                <span>Push</span>
                <span>Max</span>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  );
}
